export enum AdministratingRecordCompanyRole {}
export enum AllTerritoryCode {}
export enum ArtistRole {}
export enum BinaryDataType {}
export enum CarrierType {}
export enum ContainerFormat {}
export enum CurrentTerritoryCode {}
export enum DrmPlatformType {}
export enum ExpressionType {}
export enum ExternallyLinkedResourceType {}
export enum FingerprintAlgorithmType {}
export enum GoverningAgreementType {}
export enum HashSumAlgorithmType {}
export enum ImageCodecType {}
export enum ImageType {}
export enum IsoLanguageCode {}
export enum LabelNameType {}
export enum LanguageOfPerformance {}
export enum MembershipType {}
export enum MessageControlType {}
export enum MusicalWorkContributorRole {}
export enum ParentalWarningType {}
export enum PLineType {}
export enum Purpose {}
export enum RatingAgency {}
export enum ReleaseRelationshipType {}
export enum ReleaseResourceType {}
export enum ReleaseType {}
export enum ReasonType {}
export enum ResourceContributorRole {}
export enum ResourceOmissionReason {}
export enum ResourceType {}
export enum RightsControllerRole {}
export enum RightsControllerType {}
export enum Sex {}
export enum SoundRecordingType {}
export enum TerritoryCodeType {}
export enum TerritoryCodeTypeIncludingDeprecatedCodes {}
export enum TitleType {}
export enum UnitOfExtent {}
export enum UnitOfFrameRate {}
export enum UpdateIndicator {}
export enum UserInterfaceType {}
export enum UseType {}
