export enum ContributorRole {}
export enum CurrentTerritoryCode {}
export enum DisplayArtistRole {}
export enum MessageControlType {}
export enum ParentalWarningType {}
export enum ReleaseProfileVariantVersionId {}
export enum ReleaseProfileVersionId {}
export enum SoundRecordingType {}
export enum SubTitleType {}
